VARIABLE SCOPES
//SEPTEMBER 5, 2024 HOUR 3
//GLOBAL SCOPE
//DECLARE VARIABLES OUTSIDE OF CURLY BRACES
//ANY CODE IN THE SAME FILE HAS ACCESS TO THE VARIABLE
const PI = 3.14;
I
// FUNCTION SCOPE
//DECLARE VARIABLES IN A FUNCTION
//ONLY THE FUNCTION HAS ACCESS TO THE VARIABLES
function myFunction) f
const myVariable = 5;



const PI = 3.14;
const globalVariable = "I'm in the global scope!";
// FUNCTION SCOPE (AKA LOCAL SCOPE)
//DECLARE VARIABLES IN A FUNCTION
//ONLY THE FUNCTION HAS ACCESS TO THE VARIABLES
function myFunction()€
const myVariablE = 5;
//BLOCK SCOPE
//DECLARE VARIABLES IN CURLY BRACES
//ONLY THE CODE BLOCK HAS ACCESS TO THE VARIABLES
while (false) {
    const x = 5: